/* automatically generated by rust-bindgen 0.72.1 */

pub const AZIOT_KEYS_RC_OK: u32 = 0;
pub const AZIOT_KEYS_RC_ERR_INVALID_PARAMETER: u32 = 1;
pub const AZIOT_KEYS_RC_ERR_EXTERNAL: u32 = 2;
pub const AZIOT_KEYS_KEY_PAIR_PARAMETER_TYPE_ALGORITHM: u32 = 1;
pub const AZIOT_KEYS_KEY_PAIR_PARAMETER_TYPE_EC_CURVE_OID: u32 = 2;
pub const AZIOT_KEYS_KEY_PAIR_PARAMETER_TYPE_EC_POINT: u32 = 3;
pub const AZIOT_KEYS_KEY_PAIR_PARAMETER_TYPE_RSA_MODULUS: u32 = 4;
pub const AZIOT_KEYS_KEY_PAIR_PARAMETER_TYPE_RSA_EXPONENT: u32 = 5;
pub const AZIOT_KEYS_KEY_PAIR_PARAMETER_ALGORITHM_EC: u32 = 1;
pub const AZIOT_KEYS_KEY_PAIR_PARAMETER_ALGORITHM_RSA: u32 = 2;
pub const AZIOT_KEYS_KEY_USAGE_DERIVE: u32 = 1;
pub const AZIOT_KEYS_KEY_USAGE_ENCRYPT: u32 = 16;
pub const AZIOT_KEYS_KEY_USAGE_SIGN: u32 = 1;
pub const AZIOT_KEYS_SIGN_MECHANISM_ECDSA: u32 = 1;
pub const AZIOT_KEYS_SIGN_MECHANISM_HMAC_SHA256: u32 = 2;
pub const AZIOT_KEYS_SIGN_MECHANISM_DERIVED: u32 = 3;
pub const AZIOT_KEYS_ENCRYPT_MECHANISM_AEAD: u32 = 1;
pub const AZIOT_KEYS_ENCRYPT_MECHANISM_RSA_PKCS1: u32 = 2;
pub const AZIOT_KEYS_ENCRYPT_MECHANISM_RSA_NO_PADDING: u32 = 3;
pub const AZIOT_KEYS_ENCRYPT_MECHANISM_DERIVED: u32 = 4;
pub const AZIOT_KEYS_VERSION_2_0_0_0: u32 = 33554432;
pub const AZIOT_KEYS_VERSION_2_1_0_0: u32 = 33619968;
#[doc = " Return code of a function. This is a transparent wrapper around a `std::os::raw::c_uint` (`unsigned int`).\n\n One of the `AZIOT_KEYS_RC_ERR_*` constants."]
pub type AZIOT_KEYS_RC = ::std::os::raw::c_uint;
#[doc = " Represents the version of the API exported by this library."]
pub type AZIOT_KEYS_VERSION = ::std::os::raw::c_uint;
#[doc = " The base struct of all of function lists."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AZIOT_KEYS_FUNCTION_LIST {
    #[doc = " The version of the API represented in this function list.\n\n The specific subtype of `AZIOT_KEYS_FUNCTION_LIST` can be determined by inspecting this value."]
    pub version: AZIOT_KEYS_VERSION,
}
#[doc = " The mechanism used with `sign` / `verify`.\n\n One of the `AZIOT_KEYS_SIGN_MECHANISM_*` constants."]
pub type AZIOT_KEYS_SIGN_MECHANISM = ::std::os::raw::c_uint;
#[doc = " Used with `sign` / `verify` with the [`AZIOT_KEYS_SIGN_MECHANISM_DERIVED`] mechanism."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AZIOT_KEYS_SIGN_DERIVED_PARAMETERS {
    #[doc = " The data used to derive the new key."]
    pub derivation_data: *const ::std::os::raw::c_uchar,
    #[doc = " The length of the `derivation_data` buffer."]
    pub derivation_data_len: usize,
    #[doc = " The signature mechanism to use with the derived key.\n\n One of the `AZIOT_KEYS_SIGN_MECHANISM_*` constants."]
    pub mechanism: AZIOT_KEYS_SIGN_MECHANISM,
    #[doc = " The parameters of the signature mechanism specified by `mechanism`."]
    pub parameters: *const ::std::os::raw::c_void,
}
#[doc = " Used with `encrypt` / `decrypt` with the [`AZIOT_KEYS_ENCRYPT_MECHANISM_AEAD`] mechanism."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AZIOT_KEYS_ENCRYPT_AEAD_PARAMETERS {
    #[doc = " The IV."]
    pub iv: *const ::std::os::raw::c_uchar,
    #[doc = " The length of the `iv` buffer."]
    pub iv_len: usize,
    #[doc = " The AAD."]
    pub aad: *const ::std::os::raw::c_uchar,
    #[doc = " The length of the `aad` buffer."]
    pub aad_len: usize,
}
#[doc = " The mechanism used with `encrypt` / `decrypt`.\n\n One of the `AZIOT_KEYS_ENCRYPT_MECHANISM_*` constants."]
pub type AZIOT_KEYS_ENCRYPT_MECHANISM = ::std::os::raw::c_uint;
#[doc = " Used with `encrypt` / `decrypt` with the [`AZIOT_KEYS_ENCRYPT_MECHANISM_DERIVED`] mechanism."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AZIOT_KEYS_ENCRYPT_DERIVED_PARAMETERS {
    #[doc = " The data used to derive the new key."]
    pub derivation_data: *const ::std::os::raw::c_uchar,
    #[doc = " The length of the `derivation_data` buffer."]
    pub derivation_data_len: usize,
    #[doc = " The encryption mechanism to use with the derived key.\n\n One of the `AZIOT_KEYS_ENCRYPT_MECHANISM_*` constants."]
    pub mechanism: AZIOT_KEYS_ENCRYPT_MECHANISM,
    #[doc = " The parameters of the encryption mechanism specified by `mechanism`."]
    pub parameters: *const ::std::os::raw::c_void,
}
#[doc = " Used as the parameter type with `get_key_pair_parameter`.\n\n One of the `AZIOT_KEYS_KEY_PAIR_PARAMETER_TYPE_*` constants."]
pub type AZIOT_KEYS_KEY_PAIR_PARAMETER_TYPE = ::std::os::raw::c_uint;
#[doc = " The usage of key being created with `create_key_if_not_exists` or\n being imported with `import_key`.\n\n This is a bitflag type, so its values can be combined. But note that not all combinations of flags\n are valid."]
pub type AZIOT_KEYS_KEY_USAGE = ::std::os::raw::c_uint;
#[doc = " The specific implementation of [`AZIOT_KEYS_FUNCTION_LIST`] for API version 2.0.0.0"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AZIOT_KEYS_FUNCTION_LIST_2_0_0_0 {
    #[doc = " The value of `base.version` must be [`AZIOT_KEYS_VERSION_2_0_0_0`]."]
    pub base: AZIOT_KEYS_FUNCTION_LIST,
    #[doc = " Set a parameter on this library.\n\n `name` must not be `NULL`.\n `value` may be `NULL`.\n\n The caller may free the name string after this method returns. If the implementation needs to hold on to it, it must make a copy.\n\n The interpretation of names and values depends on the implementation. A special case is for names that start with `preloaded_key:`,\n such as `preloaded_key:foo`. This defines a user-provided association of the key ID \"foo\" with the location specified by `value`.\n Any call that uses the key with ID \"foo\" must use the location specified by `value`. Note that this does not mean the key already exists\n at that location; but it does mean that `create_key_if_not_exists` (for example) must create the key at that location and not any other.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `name` is `NULL`.\n   - `name` is not recognized by this implementation, or invalid in some other way.\n   - `value` is invalid.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub set_parameter: ::std::option::Option<
        unsafe extern "C" fn(
            name: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Create or load a key pair identified by the specified `id`.\n\n - If a key pair with that ID exists and can be loaded, it will be left as-is.\n - If a key pair with that ID does not exist, a new key will be created. It will be saved such that it can be looked up later using that same ID.\n\n `preferred_algorithms` dictates the caller's preference for the key algorithm. It is a string with components separated by COLON U+003A `:`,\n where each component specifies the name of an algorithm and will be attempted by the implementation in that order.\n The valid components are `\"ec-p256\"` for secp256r1, `\"rsa-2048\"` for 2048-bit RSA, `\"rsa-4096\"` for 4096-bit RSA, and `\"*\"` which indicates\n any algorithm of the implementation's choice. For example, the caller might use `\"ec-p256:rsa-2048:*\"` to indicate that it would like\n the implementation to use secp256r1, else RSA-2048 if that fails, else any other algorithm of the implementation's choice if that also fails.\n\n If an implementation does not recognize a particular component as an algorithm, or is unable to use the algorithm to generate a key pair,\n it must ignore that component and try the next one. If no components are left, the implementation returns an error.\n The implementation is allowed to be unable to generate a key pair regardless of which algorithms are specified; this is true even if\n the wildcard algorithm is specified.\n\n If `preferred_algorithms` is `NULL`, it must be interpreted the same as if it was `\"*\"`.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - `preferred_algorithms` is invalid.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub create_key_pair_if_not_exists: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            preferred_algorithms: *const ::std::os::raw::c_char,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Load an existing key pair identified by the specified `id`.\n\n This validates that a key pair with the given ID exists and can be loaded.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub load_key_pair: ::std::option::Option<
        unsafe extern "C" fn(id: *const ::std::os::raw::c_char) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Get the value of a parameter of the key pair identified by the specified `id`.\n\n `type_` must be set to one of the `AZIOT_KEYS_KEY_PAIR_PARAMETER_TYPE_*` constants.\n\n `value` is an output byte buffer allocated by the caller to store the parameter value.\n The caller sets `value_len` to the address of the length of the buffer.\n The implementation populates `value` with the parameter value and sets `value_len` to the number of bytes it wrote to `value`.\n\n It is allowed for the caller to call the function with `value` set to `NULL`. In this case the implementation calculates\n an upper bound for how many bytes will be needed to store the parameter value, sets that in `value_len` and returns.\n\n The format of the data stored in `value` is determined by the `type_`. See the documentation of those constants for details.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - The key pair specified by `id` does not exist.\n   - `type_` is not a valid parameter type for the key pair specified by `id`.\n   - `value` is insufficiently large to hold the parameter value.\n   - `value_len` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub get_key_pair_parameter: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            type_: AZIOT_KEYS_KEY_PAIR_PARAMETER_TYPE,
            value: *mut ::std::os::raw::c_uchar,
            value_len: *mut usize,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Create or load a key identified by the specified `id`.\n\n - If a key with that ID exists and can be loaded, it will be left as-is.\n - If a key with that ID does not exist, a new random key will be created.\n   It will be saved such that it can be looked up later using that same ID.\n\n `usage` specifies what the key will be used for.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub create_key_if_not_exists: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            usage: AZIOT_KEYS_KEY_USAGE,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Load an existing key identified by the specified `id`.\n\n This validates that a key with the given ID exists and can be loaded.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - The key specified by `id` does not exist.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub load_key: ::std::option::Option<
        unsafe extern "C" fn(id: *const ::std::os::raw::c_char) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Import a symmetric key with the given `id`.\n\n It will be saved such that it can be looked up later using that same ID.\n\n If a key with that ID already exists, the existing key will be overwritten.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - `bytes` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub import_key: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            bytes: *const u8,
            bytes_len: usize,
            usage: AZIOT_KEYS_KEY_USAGE,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Derive a key with a given base key using some derivation data, and return the derived key.\n\n The derivation process used by this function must be identical to\n the derivation process used by `encrypt` with the `AZIOT_KEYS_ENCRYPT_MECHANISM_DERIVED` mechanism and\n the derivation process used by `sign` with the `AZIOT_KEYS_SIGN_MECHANISM_DERIVED` mechanism.\n\n `base_id` is the ID of the key that will be used to derive the new key. The key must have been created / imported\n with the [`crate::AZIOT_KEYS_KEY_USAGE_DERIVE`] usage.\n\n `derivation_data` is a byte buffer containing the data that used for the derivation.\n The caller sets `derivation_data_len` to the length of the buffer.\n\n `derived_key` is an output byte buffer allocated by the caller to store the derived key.\n The caller sets `derived_key_len` to the address of the length of the buffer.\n The implementation populates `derived_key` with the derived key and sets `derived_key_len` to the number of bytes it wrote to `derived_key`.\n\n It is allowed for the caller to call the function with `derived_key` set to `NULL`. In this case the implementation calculates\n an upper bound for how many bytes will be needed to store the derived key, sets that in `derived_key_len` and returns.\n\n The new key is not persisted by the implementation, only returned in `derived_key`.\n If the caller wishes to persist it, they can import it with `import_key`.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `base_id` is `NULL`.\n   - `base_id` is invalid.\n   - The key specified by `base_id` does not exist.\n   - `derivation_data` is `NULL`.\n   - `derived_key` is insufficiently large to hold the parameter value.\n   - `derived_key_len` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub derive_key: ::std::option::Option<
        unsafe extern "C" fn(
            base_id: *const ::std::os::raw::c_char,
            derivation_data: *const u8,
            derivation_data_len: usize,
            derived_key: *mut ::std::os::raw::c_uchar,
            derived_key_len: *mut usize,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Sign the given digest using the key or key pair identified by the specified `id`.\n\n `mechanism` must be set to one of the `AZIOT_KEYS_SIGN_MECHANISM_*` constants.\n `parameters` must be set according to the `mechanism`, as documented on the constants.\n\n `digest` is a byte buffer containing the data that must be signed.\n The caller sets `digest_len` to the length of the buffer.\n\n `signature` is an output byte buffer allocated by the caller to store the signature.\n The caller sets `signature_len` to the address of the length of the buffer.\n The implementation populates `signature` with the signature and sets `signature_len` to the number of bytes it wrote to `signature`.\n\n It is allowed for the caller to call the function with `signature` set to `NULL`. In this case the implementation calculates\n an upper bound for how many bytes will be needed to store the signature, sets that in `signature_len` and returns.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - The key or key pair specified by `id` does not exist.\n   - `mechanism` is not a valid signature mechanism for the key or key pair specified by `id`.\n   - `parameters` is invalid.\n   - `digest` is `NULL`.\n   - `signature` is insufficiently large to hold the signature.\n   - `signature_len` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub sign: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            mechanism: AZIOT_KEYS_SIGN_MECHANISM,
            parameters: *const ::std::os::raw::c_void,
            digest: *const ::std::os::raw::c_uchar,
            digest_len: usize,
            signature: *mut ::std::os::raw::c_uchar,
            signature_len: *mut usize,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Verify the signature of the given digest using the key or key pair (but see note below) identified by the specified `id`.\n\n `mechanism` must be set to one of the `AZIOT_KEYS_SIGN_MECHANISM_*` constants.\n `parameters` must be set according to the `mechanism`, as documented on the constants.\n\n `digest` is a byte buffer containing the data that must be signed.\n The caller sets `digest_len` to the length of the buffer.\n\n `signature` is a byte buffer containing the signature that the caller expects the data to have.\n The caller sets `signature_len` to the length of the buffer.\n\n `ok` is an output parameter that stores whether the signature could be verified or not.\n If the function is able to compute the signature of the data, it sets `ok` and returns `AZIOT_KEYS_RC_OK`.\n `ok` is set to 0 if the signature is invalid and non-zero if the signature is valid.\n The value stored in `ok` is only meaningful if the function returns `AZIOT_KEYS_RC_OK`, otherwise it must be ignored.\n\n Note: The implementation is not required to support verification with key pairs, ie `AZIOT_KEYS_SIGN_MECHANISM_ECDSA`.\n The caller can do the verification themselves with the public parameters of the EC key as obtained via `get_key_pair_parameter`.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - The key or key pair specified by `id` does not exist.\n   - `mechanism` is not a valid signature mechanism for the key or key pair specified by `id`.\n   - `parameters` is invalid.\n   - `digest` is `NULL`.\n   - `signature` is `NULL`.\n   - `ok` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub verify: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            mechanism: AZIOT_KEYS_SIGN_MECHANISM,
            parameters: *const ::std::os::raw::c_void,
            digest: *const ::std::os::raw::c_uchar,
            digest_len: usize,
            signature: *const ::std::os::raw::c_uchar,
            signature_len: usize,
            ok: *mut ::std::os::raw::c_int,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Encrypt the given plaintext using the key or key pair identified by the specified `id`.\n\n `mechanism` must be set to one of the `AZIOT_KEYS_ENCRYPT_MECHANISM_*` constants.\n `parameters` must be set according to the `mechanism`, as documented on the constants.\n\n `plaintext` is a byte buffer containing the data that must be encrypted.\n The caller sets `plaintext_len` to the length of the buffer.\n\n `ciphertext` is an output byte buffer allocated by the caller to store the encrypted data.\n The caller sets `ciphertext_len` to the address of the length of the buffer.\n The implementation populates `ciphertext` with the ciphertext and sets `ciphertext_len` to the number of bytes it wrote to `ciphertext`.\n\n It is allowed for the caller to call the function with `ciphertext` set to `NULL`. In this case the implementation calculates\n an upper bound for how many bytes will be needed to store the ciphertext, sets that in `ciphertext_len` and returns.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - The key or key pair specified by `id` does not exist.\n   - `mechanism` is not a valid encryption mechanism for the key or key pair specified by `id`.\n   - `parameters` is invalid.\n   - `plaintext` is `NULL`.\n   - `ciphertext` is insufficiently large to hold the ciphertext.\n   - `ciphertext_len` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub encrypt: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            mechanism: AZIOT_KEYS_ENCRYPT_MECHANISM,
            parameters: *const ::std::os::raw::c_void,
            plaintext: *const ::std::os::raw::c_uchar,
            plaintext_len: usize,
            ciphertext: *mut ::std::os::raw::c_uchar,
            ciphertext_len: *mut usize,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Decrypt the given plaintext using the key or key pair identified by the specified `id`.\n\n `mechanism` must be set to one of the `AZIOT_KEYS_ENCRYPT_MECHANISM_*` constants.\n `parameters` must be set according to the `mechanism`, as documented on the constants.\n\n `ciphertext` is a byte buffer containing the data that must be signed.\n The caller sets `ciphertext_len` to the length of the buffer.\n\n `plaintext` is an output byte buffer allocated by the caller to store the decrypted data.\n The caller sets `plaintext_len` to the address of the length of the buffer.\n The implementation populates `plaintext` with the plaintext and sets `plaintext_len` to the number of bytes it wrote to `plaintext`.\n\n It is allowed for the caller to call the function with `plaintext` set to `NULL`. In this case the implementation calculates\n an upper bound for how many bytes will be needed to store the plaintext, sets that in `plaintext_len` and returns.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - The key or key pair specified by `id` does not exist.\n   - `mechanism` is not a valid encryption mechanism for the key or key pair specified by `id`.\n   - `parameters` is invalid.\n   - `ciphertext` is `NULL`.\n   - `plaintext` is insufficiently large to hold the ciphertext.\n   - `plaintext_len` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub decrypt: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            mechanism: AZIOT_KEYS_ENCRYPT_MECHANISM,
            parameters: *const ::std::os::raw::c_void,
            ciphertext: *const ::std::os::raw::c_uchar,
            ciphertext_len: usize,
            plaintext: *mut ::std::os::raw::c_uchar,
            plaintext_len: *mut usize,
        ) -> AZIOT_KEYS_RC,
    >,
}
#[doc = " The specific implementation of [`AZIOT_KEYS_FUNCTION_LIST`] for API version 2.1.0.0"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AZIOT_KEYS_FUNCTION_LIST_2_1_0_0 {
    #[doc = " The value of `base.version` must be [`AZIOT_KEYS_VERSION_2_1_0_0`]."]
    pub base: AZIOT_KEYS_FUNCTION_LIST,
    #[doc = " Set a parameter on this library.\n\n `name` must not be `NULL`.\n `value` may be `NULL`.\n\n The caller may free the name string after this method returns. If the implementation needs to hold on to it, it must make a copy.\n\n The interpretation of names and values depends on the implementation. A special case is for names that start with `preloaded_key:`,\n such as `preloaded_key:foo`. This defines a user-provided association of the key ID \"foo\" with the location specified by `value`.\n Any call that uses the key with ID \"foo\" must use the location specified by `value`. Note that this does not mean the key already exists\n at that location; but it does mean that `create_key_if_not_exists` (for example) must create the key at that location and not any other.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `name` is `NULL`.\n   - `name` is not recognized by this implementation, or invalid in some other way.\n   - `value` is invalid.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub set_parameter: ::std::option::Option<
        unsafe extern "C" fn(
            name: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Create or load a key pair identified by the specified `id`.\n\n - If a key pair with that ID exists and can be loaded, it will be left as-is.\n - If a key pair with that ID does not exist, a new key will be created. It will be saved such that it can be looked up later using that same ID.\n\n `preferred_algorithms` dictates the caller's preference for the key algorithm. It is a string with components separated by COLON U+003A `:`,\n where each component specifies the name of an algorithm and will be attempted by the implementation in that order.\n The valid components are `\"ec-p256\"` for secp256r1, `\"rsa-2048\"` for 2048-bit RSA, `\"rsa-4096\"` for 4096-bit RSA, and `\"*\"` which indicates\n any algorithm of the implementation's choice. For example, the caller might use `\"ec-p256:rsa-2048:*\"` to indicate that it would like\n the implementation to use secp256r1, else RSA-2048 if that fails, else any other algorithm of the implementation's choice if that also fails.\n\n If an implementation does not recognize a particular component as an algorithm, or is unable to use the algorithm to generate a key pair,\n it must ignore that component and try the next one. If no components are left, the implementation returns an error.\n The implementation is allowed to be unable to generate a key pair regardless of which algorithms are specified; this is true even if\n the wildcard algorithm is specified.\n\n If `preferred_algorithms` is `NULL`, it must be interpreted the same as if it was `\"*\"`.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - `preferred_algorithms` is invalid.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub create_key_pair_if_not_exists: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            preferred_algorithms: *const ::std::os::raw::c_char,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Move an existing key pair to another `id`.\n\n This function replaces any existing key and the destination `id`.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - either `from` or `to` is `NULL`.\n   - either `from` or `to` is invalid.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub move_key_pair: ::std::option::Option<
        unsafe extern "C" fn(
            from: *const ::std::os::raw::c_char,
            to: *const ::std::os::raw::c_char,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Load an existing key pair identified by the specified `id`.\n\n This validates that a key pair with the given ID exists and can be loaded.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub load_key_pair: ::std::option::Option<
        unsafe extern "C" fn(id: *const ::std::os::raw::c_char) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Get the value of a parameter of the key pair identified by the specified `id`.\n\n `type_` must be set to one of the `AZIOT_KEYS_KEY_PAIR_PARAMETER_TYPE_*` constants.\n\n `value` is an output byte buffer allocated by the caller to store the parameter value.\n The caller sets `value_len` to the address of the length of the buffer.\n The implementation populates `value` with the parameter value and sets `value_len` to the number of bytes it wrote to `value`.\n\n It is allowed for the caller to call the function with `value` set to `NULL`. In this case the implementation calculates\n an upper bound for how many bytes will be needed to store the parameter value, sets that in `value_len` and returns.\n\n The format of the data stored in `value` is determined by the `type_`. See the documentation of those constants for details.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - The key pair specified by `id` does not exist.\n   - `type_` is not a valid parameter type for the key pair specified by `id`.\n   - `value` is insufficiently large to hold the parameter value.\n   - `value_len` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub get_key_pair_parameter: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            type_: AZIOT_KEYS_KEY_PAIR_PARAMETER_TYPE,
            value: *mut ::std::os::raw::c_uchar,
            value_len: *mut usize,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Delete an existing key pair identified by the specified `id`.\n\n This function succeeds if a key with the specified ID doesn't already exist.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub delete_key_pair: ::std::option::Option<
        unsafe extern "C" fn(id: *const ::std::os::raw::c_char) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Create or load a key identified by the specified `id`.\n\n - If a key with that ID exists and can be loaded, it will be left as-is.\n - If a key with that ID does not exist, a new random key will be created.\n   It will be saved such that it can be looked up later using that same ID.\n\n `usage` specifies what the key will be used for.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub create_key_if_not_exists: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            usage: AZIOT_KEYS_KEY_USAGE,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Load an existing key identified by the specified `id`.\n\n This validates that a key with the given ID exists and can be loaded.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - The key specified by `id` does not exist.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub load_key: ::std::option::Option<
        unsafe extern "C" fn(id: *const ::std::os::raw::c_char) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Import a symmetric key with the given `id`.\n\n It will be saved such that it can be looked up later using that same ID.\n\n If a key with that ID already exists, the existing key will be overwritten.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - `bytes` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub import_key: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            bytes: *const u8,
            bytes_len: usize,
            usage: AZIOT_KEYS_KEY_USAGE,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Delete an existing key identified by the specified `id`.\n\n This function succeeds if a key with the specified ID doesn't already exist.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub delete_key: ::std::option::Option<
        unsafe extern "C" fn(id: *const ::std::os::raw::c_char) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Derive a key with a given base key using some derivation data, and return the derived key.\n\n The derivation process used by this function must be identical to\n the derivation process used by `encrypt` with the `AZIOT_KEYS_ENCRYPT_MECHANISM_DERIVED` mechanism and\n the derivation process used by `sign` with the `AZIOT_KEYS_SIGN_MECHANISM_DERIVED` mechanism.\n\n `base_id` is the ID of the key that will be used to derive the new key. The key must have been created / imported\n with the [`crate::AZIOT_KEYS_KEY_USAGE_DERIVE`] usage.\n\n `derivation_data` is a byte buffer containing the data that used for the derivation.\n The caller sets `derivation_data_len` to the length of the buffer.\n\n `derived_key` is an output byte buffer allocated by the caller to store the derived key.\n The caller sets `derived_key_len` to the address of the length of the buffer.\n The implementation populates `derived_key` with the derived key and sets `derived_key_len` to the number of bytes it wrote to `derived_key`.\n\n It is allowed for the caller to call the function with `derived_key` set to `NULL`. In this case the implementation calculates\n an upper bound for how many bytes will be needed to store the derived key, sets that in `derived_key_len` and returns.\n\n The new key is not persisted by the implementation, only returned in `derived_key`.\n If the caller wishes to persist it, they can import it with `import_key`.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `base_id` is `NULL`.\n   - `base_id` is invalid.\n   - The key specified by `base_id` does not exist.\n   - `derivation_data` is `NULL`.\n   - `derived_key` is insufficiently large to hold the parameter value.\n   - `derived_key_len` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub derive_key: ::std::option::Option<
        unsafe extern "C" fn(
            base_id: *const ::std::os::raw::c_char,
            derivation_data: *const u8,
            derivation_data_len: usize,
            derived_key: *mut ::std::os::raw::c_uchar,
            derived_key_len: *mut usize,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Sign the given digest using the key or key pair identified by the specified `id`.\n\n `mechanism` must be set to one of the `AZIOT_KEYS_SIGN_MECHANISM_*` constants.\n `parameters` must be set according to the `mechanism`, as documented on the constants.\n\n `digest` is a byte buffer containing the data that must be signed.\n The caller sets `digest_len` to the length of the buffer.\n\n `signature` is an output byte buffer allocated by the caller to store the signature.\n The caller sets `signature_len` to the address of the length of the buffer.\n The implementation populates `signature` with the signature and sets `signature_len` to the number of bytes it wrote to `signature`.\n\n It is allowed for the caller to call the function with `signature` set to `NULL`. In this case the implementation calculates\n an upper bound for how many bytes will be needed to store the signature, sets that in `signature_len` and returns.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - The key or key pair specified by `id` does not exist.\n   - `mechanism` is not a valid signature mechanism for the key or key pair specified by `id`.\n   - `parameters` is invalid.\n   - `digest` is `NULL`.\n   - `signature` is insufficiently large to hold the signature.\n   - `signature_len` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub sign: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            mechanism: AZIOT_KEYS_SIGN_MECHANISM,
            parameters: *const ::std::os::raw::c_void,
            digest: *const ::std::os::raw::c_uchar,
            digest_len: usize,
            signature: *mut ::std::os::raw::c_uchar,
            signature_len: *mut usize,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Verify the signature of the given digest using the key or key pair (but see note below) identified by the specified `id`.\n\n `mechanism` must be set to one of the `AZIOT_KEYS_SIGN_MECHANISM_*` constants.\n `parameters` must be set according to the `mechanism`, as documented on the constants.\n\n `digest` is a byte buffer containing the data that must be signed.\n The caller sets `digest_len` to the length of the buffer.\n\n `signature` is a byte buffer containing the signature that the caller expects the data to have.\n The caller sets `signature_len` to the length of the buffer.\n\n `ok` is an output parameter that stores whether the signature could be verified or not.\n If the function is able to compute the signature of the data, it sets `ok` and returns `AZIOT_KEYS_RC_OK`.\n `ok` is set to 0 if the signature is invalid and non-zero if the signature is valid.\n The value stored in `ok` is only meaningful if the function returns `AZIOT_KEYS_RC_OK`, otherwise it must be ignored.\n\n Note: The implementation is not required to support verification with key pairs, ie `AZIOT_KEYS_SIGN_MECHANISM_ECDSA`.\n The caller can do the verification themselves with the public parameters of the EC key as obtained via `get_key_pair_parameter`.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - The key or key pair specified by `id` does not exist.\n   - `mechanism` is not a valid signature mechanism for the key or key pair specified by `id`.\n   - `parameters` is invalid.\n   - `digest` is `NULL`.\n   - `signature` is `NULL`.\n   - `ok` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub verify: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            mechanism: AZIOT_KEYS_SIGN_MECHANISM,
            parameters: *const ::std::os::raw::c_void,
            digest: *const ::std::os::raw::c_uchar,
            digest_len: usize,
            signature: *const ::std::os::raw::c_uchar,
            signature_len: usize,
            ok: *mut ::std::os::raw::c_int,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Encrypt the given plaintext using the key or key pair identified by the specified `id`.\n\n `mechanism` must be set to one of the `AZIOT_KEYS_ENCRYPT_MECHANISM_*` constants.\n `parameters` must be set according to the `mechanism`, as documented on the constants.\n\n `plaintext` is a byte buffer containing the data that must be encrypted.\n The caller sets `plaintext_len` to the length of the buffer.\n\n `ciphertext` is an output byte buffer allocated by the caller to store the encrypted data.\n The caller sets `ciphertext_len` to the address of the length of the buffer.\n The implementation populates `ciphertext` with the ciphertext and sets `ciphertext_len` to the number of bytes it wrote to `ciphertext`.\n\n It is allowed for the caller to call the function with `ciphertext` set to `NULL`. In this case the implementation calculates\n an upper bound for how many bytes will be needed to store the ciphertext, sets that in `ciphertext_len` and returns.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - The key or key pair specified by `id` does not exist.\n   - `mechanism` is not a valid encryption mechanism for the key or key pair specified by `id`.\n   - `parameters` is invalid.\n   - `plaintext` is `NULL`.\n   - `ciphertext` is insufficiently large to hold the ciphertext.\n   - `ciphertext_len` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub encrypt: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            mechanism: AZIOT_KEYS_ENCRYPT_MECHANISM,
            parameters: *const ::std::os::raw::c_void,
            plaintext: *const ::std::os::raw::c_uchar,
            plaintext_len: usize,
            ciphertext: *mut ::std::os::raw::c_uchar,
            ciphertext_len: *mut usize,
        ) -> AZIOT_KEYS_RC,
    >,
    #[doc = " Decrypt the given plaintext using the key or key pair identified by the specified `id`.\n\n `mechanism` must be set to one of the `AZIOT_KEYS_ENCRYPT_MECHANISM_*` constants.\n `parameters` must be set according to the `mechanism`, as documented on the constants.\n\n `ciphertext` is a byte buffer containing the data that must be signed.\n The caller sets `ciphertext_len` to the length of the buffer.\n\n `plaintext` is an output byte buffer allocated by the caller to store the decrypted data.\n The caller sets `plaintext_len` to the address of the length of the buffer.\n The implementation populates `plaintext` with the plaintext and sets `plaintext_len` to the number of bytes it wrote to `plaintext`.\n\n It is allowed for the caller to call the function with `plaintext` set to `NULL`. In this case the implementation calculates\n an upper bound for how many bytes will be needed to store the plaintext, sets that in `plaintext_len` and returns.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `id` is `NULL`.\n   - `id` is invalid.\n   - The key or key pair specified by `id` does not exist.\n   - `mechanism` is not a valid encryption mechanism for the key or key pair specified by `id`.\n   - `parameters` is invalid.\n   - `ciphertext` is `NULL`.\n   - `plaintext` is insufficiently large to hold the ciphertext.\n   - `plaintext_len` is `NULL`.\n\n - `AZIOT_KEYS_RC_ERR_EXTERNAL`"]
    pub decrypt: ::std::option::Option<
        unsafe extern "C" fn(
            id: *const ::std::os::raw::c_char,
            mechanism: AZIOT_KEYS_ENCRYPT_MECHANISM,
            parameters: *const ::std::os::raw::c_void,
            ciphertext: *const ::std::os::raw::c_uchar,
            ciphertext_len: usize,
            plaintext: *mut ::std::os::raw::c_uchar,
            plaintext_len: *mut usize,
        ) -> AZIOT_KEYS_RC,
    >,
}
#[doc = " The algorithm of a key pair, as returned by `get_key_pair_parameter`.\n\n One of the `AZIOT_KEYS_KEY_PAIR_PARAMETER_ALGORITHM_*` constants."]
pub type AZIOT_KEYS_KEY_PAIR_PARAMETER_ALGORITHM = ::std::os::raw::c_uint;
unsafe extern "C" {
    #[doc = " Get the list of functions for operations corresponding to the specified version.\n\n Implementations can use this function for initialization, since it is guaranteed to be called before any operations.\n However it is not an error to call this function multiple times, for the same or different version,\n so implementations must ensure they only run their initialization once.\n\n The pointer returned from this function must not be freed by the caller, and its contents must not be mutated.\n\n # Errors\n\n - `AZIOT_KEYS_RC_ERR_INVALID_PARAMETER`:\n   - `version` is not recognized by this implementation.\n   - `pfunction_list` is `NULL`.\n\n # Safety\n\n `pfunction_list` must point to a valid writable location."]
    pub fn aziot_keys_get_function_list(
        version: AZIOT_KEYS_VERSION,
        pfunction_list: *mut *const AZIOT_KEYS_FUNCTION_LIST,
    ) -> AZIOT_KEYS_RC;
}
