trigger: none
pr:
  branches:
    include:
      - thud
jobs:

################################################################################
  - job: thud
################################################################################
    displayName: Thud
    pool:
      name: azureiotedge
      demands:
        - yocto
    timeoutInMinutes: 360
    steps:
      - script: scripts/fetch.sh thud
        displayName: Fetch
        env:
          METARUST_REV: 'refs/remotes/origin/master'
      - script: scripts/build.sh
        displayName: Build
