trigger: none
pr:
  branches:
    include:
      - main
      - sumo
      - thud
      - warrior
      - zeus
      - dunfell
jobs:

################################################################################
  - job: kirkstone
################################################################################
    displayName: Kirkstone
    pool:
      name: meta-iotedge-1es-hosted-linux
      demands:
      - ImageOverride -equals agent-aziotedge-ubuntu-20.04-msmoby
      - DiskSizeGiB -equals 500
      - WorkFolder -equals /mnt/storage/_work
    timeoutInMinutes: 2400
    steps:
      - script: scripts/fetch.sh kirkstone
        displayName: Fetch
        env:
          METARUST_REV: '5656b5ad104bbbbe1b711e3bbe35c88f0d9c9a05'

      - script: scripts/build.sh
        displayName: Build
