trigger: none
pr:
  branches:
    include:
      - master
      - warrior
jobs:

################################################################################
  - job: warrior
################################################################################
    displayName: Warrior
    pool:
      name: azureiotedge
      demands:
        - yocto
    timeoutInMinutes: 360
    steps:
      - script: scripts/fetch.sh warrior
        displayName: Fetch
        env:
          METARUST_REV: 'refs/remotes/origin/master'
      - script: scripts/build.sh
        displayName: Build
