trigger: none
pr:
  branches:
    include:
      - master
      - sumo
      - thud
      - warrior
      - zeus
      - dunfell
jobs:

################################################################################
  - job: honister
################################################################################
    displayName: Honister
    pool:
      name: azureiotedge
      demands:
        - yocto
    timeoutInMinutes: 360
    steps:
      - script: scripts/fetch.sh honister
        displayName: Fetch
        env:
          METARUST_REV: 'refs/remotes/origin/master'
      - script: scripts/build.sh
        displayName: Build
