trigger: none
pr:
  branches:
    include:
      - master
      - zeus
jobs:

################################################################################
  - job: zeus
################################################################################
    displayName: Zeus
    pool:
      name: azureiotedge
      demands:
        - yocto
    timeoutInMinutes: 360
    steps:
      - script: scripts/fetch.sh zeus
        displayName: Fetch
        env:
          METARUST_REV: 'd8d77be1292064a02adcb5e72e293604b704f69b'
      - script: scripts/build.sh
        displayName: Build
