trigger: none
pr:
  branches:
    include:
      - main
      - kirkstone
jobs:

################################################################################
  - job: scarthgap
################################################################################
    displayName: Scarthgap
    pool:
      name: meta-iotedge-1es-hosted-linux
      demands:
      - ImageOverride -equals agent-aziotedge-ubuntu-20.04-msmoby
      - DiskSizeGiB -equals 500
      - WorkFolder -equals /mnt/storage/_work
    timeoutInMinutes: 2400
    steps:
      - script: scripts/fetch.sh scarthgap
        displayName: Fetch

      - script: scripts/build.sh
        displayName: Build
