trigger: none
pr:
  branches:
    include:
      - master
      - dunfell
jobs:

################################################################################
  - job: dunfell
################################################################################
    displayName: Dunfell
    pool:
      name: "Azure-IoT-Edge-1ES-Hosted-Linux"
      demands:
      - ImageOverride -equals agent-aziotedge-rhel-8-msmoby
    timeoutInMinutes: 360
    steps:
      - script: scripts/fetch.sh dunfell
        displayName: Fetch
        env:
          METARUST_REV: '7ff669d8cedd83a2d3efb73073a63b0a7efffddc'
      - script: scripts/build.sh
        displayName: Build