trigger: none
pr:
  branches:
    include:
      - master
      - dunfell
jobs:

################################################################################
  - job: dunfell
################################################################################
    displayName: Dunfell
    pool:
      name: meta-iotedge-1es-hosted-linux
      demands:
      - ImageOverride -equals agent-aziotedge-ubuntu-20.04-msmoby
      - DiskSizeGiB -equals 500
      - WorkFolder -equals /mnt/storage/_work
    timeoutInMinutes: 2400
    steps:
      - script: scripts/fetch.sh dunfell
        displayName: Fetch
        env:
          METARUST_REV: '1ed669c464a113cddba8222b419565273d3410f2'
      - script: scripts/build.sh
        displayName: Build
