trigger: none
pr:
  branches:
    include:
      - main
      - sumo
      - thud
      - warrior
      - zeus
      - dunfell
jobs:

################################################################################
  - job: kirkstone
################################################################################
    displayName: Kirkstone
    pool:
      name: meta-iotedge-1es-hosted-linux
      demands:
      - ImageOverride -equals agent-aziotedge-ubuntu-20.04-msmoby
      - DiskSizeGiB -equals 500
      - WorkFolder -equals /mnt/storage/_work
    timeoutInMinutes: 2400
    steps:
      - script: scripts/fetch.sh kirkstone
        displayName: Fetch
        env:
          METARUST_REV: '9611b42d73c7546c3d845da380943a0a4f4205f0'

      - script: scripts/build.sh
        displayName: Build
