trigger: none
pr:
  branches:
    include:
      - master
      - dunfell
jobs:

################################################################################
  - job: dunfell
################################################################################
    displayName: Dunfell
    pool:
      name: "iotedge-1es-hosted-linux"
      demands:
      - ImageOverride -equals agent-aziotedge-ubuntu-20.04-msmoby
      - DiskSizeGiB -equals 150
      - WorkFolder -equals /mnt/storage/_work
    timeoutInMinutes: 2400
    variables:
      mntStorageLocation: '/mnt/storage'
    steps:
      - script: scripts/fetch.sh dunfell
        displayName: Fetch
        env:
          METARUST_REV: '7ff669d8cedd83a2d3efb73073a63b0a7efffddc'
          STORAGE_PATH: $(mntStorageLocation)
      - script: scripts/build.sh
        displayName: Build
        env:
          STORAGE_PATH: $(mntStorageLocation)
      - script: |
          echo "du"
          sudo du -hsx /* | sort -rh | head -n 40
          echo ""
          echo "df"
          sudo df -ha /dev/*
        displayName: Debug disk
        condition: always()