trigger: none
pr:
  branches:
    include:
      - master
      - zeus
jobs:

################################################################################
  - job: zeus
################################################################################
    displayName: Zeus
    pool:
      name: azureiotedge
      demands:
        - yocto
    timeoutInMinutes: 360
    steps:
      - script: scripts/fetch.sh zeus
        displayName: Fetch
        env:
          METARUST_REV: '7ff669d8cedd83a2d3efb73073a63b0a7efffddc'
      - script: scripts/build.sh
        displayName: Build
