trigger: none
pr:
  branches:
    include:
      - master
      - sumo
      - thud
      - warrior
      - dunfell
jobs:

################################################################################
  - job: sumo
################################################################################
    displayName: Sumo
    pool:
      name: azureiotedge
      demands:
        - yocto
    timeoutInMinutes: 360
    steps:
      - script: scripts/fetch.sh sumo
        displayName: Fetch
        env:
          METARUST_REV: 'refs/remotes/origin/master'
      - script: scripts/build.sh
        displayName: Build
