trigger: none
pr:
  branches:
    include:
      - master
      - gatesgarth
jobs:

################################################################################
  - job: gatesgarth
################################################################################
    displayName: Gatesgarth
    pool:
      name: azureiotedge
      demands:
        - yocto
    timeoutInMinutes: 360
    steps:
      - script: scripts/fetch.sh gatesgarth
        displayName: Fetch
        env:
          METARUST_REV: 'e4d25b98083bcecb94df6ee189a165d63ede7f3d'
      - script: scripts/build.sh
        displayName: Build
