trigger: none
pr:
  branches:
    include:
      - main
      - kirkstone
jobs:

################################################################################
  - job: kirkstone
################################################################################
    displayName: Kirkstone
    pool:
      name: meta-iotedge-1es-hosted-linux
      demands:
      - ImageOverride -equals agent-aziotedge-ubuntu-20.04-msmoby
      - DiskSizeGiB -equals 500
      - WorkFolder -equals /mnt/storage/_work
    timeoutInMinutes: 2400
    steps:
      - script: scripts/fetch.sh kirkstone
        displayName: Fetch
        env:
          METARUST_REV: '93f551996e95f45e298259937c0975a2e6663911'
      - script: scripts/build.sh kirkstone
        displayName: Build